# Generated by Django 2.2 on 2020-10-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='services',
        ),
        migrations.AddField(
            model_name='ownership',
            name='services',
            field=models.ManyToManyField(to='ownerships.Service', verbose_name='list of sites'),
        ),
    ]
