# Generated by Django 2.2 on 2020-10-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0002_auto_20201010_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='name',
        ),
    ]
