# Generated by Django 2.2 on 2020-10-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0003_auto_20201010_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownership',
            options={'verbose_name': 'Ownership', 'verbose_name_plural': 'Ownerships'},
        ),
    ]
