# Generated by Django 2.2 on 2020-10-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0004_auto_20201010_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownership',
            options={},
        ),
    ]
