# Generated by Django 2.2 on 2020-10-10 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0006_auto_20201010_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='maxPeopleAmount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
