# Generated by Django 2.2 on 2020-10-10 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0007_auto_20201010_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='maxDate',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='minDate',
        ),
        migrations.AddField(
            model_name='ownership',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
