# Generated by Django 2.2 on 2020-10-10 21:34

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0008_auto_20201010_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minDate', models.DateField(default=datetime.datetime.now)),
                ('maxDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='ownership',
            name='dailyRate',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ownerships.City'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='services',
            field=models.ManyToManyField(to='ownerships.Service', verbose_name='list of services'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='rentDates',
            field=models.ManyToManyField(to='ownerships.RentDate', verbose_name='list of rent dates'),
        ),
    ]
