# Generated by Django 2.2 on 2020-10-10 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0008_auto_20201010_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minDate', models.DateField(default=datetime.datetime.now)),
                ('maxDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
