# Generated by Django 2.2 on 2020-10-10 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0009_auto_20201010_1834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentDate',
            new_name='RentPeriod',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='rentDates',
        ),
        migrations.AddField(
            model_name='ownership',
            name='rentPeriods',
            field=models.ManyToManyField(to='ownerships.RentPeriod', verbose_name='list of rent periods'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='maxPeopleAmount',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
