# Generated by Django 2.2 on 2020-10-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0010_ownership_rentdates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentDates',
            new_name='RentDate',
        ),
    ]
