# Generated by Django 2.2 on 2020-10-11 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0011_auto_20201011_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ownership',
            name='maxPeopleAmount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name=' max people amount'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='comforts',
            field=models.ManyToManyField(to='ownerships.Comfort', verbose_name='list of comforts'),
        ),
    ]
