# Generated by Django 2.2 on 2020-10-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0012_auto_20201011_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='comforts',
        ),
        migrations.DeleteModel(
            name='Comfort',
        ),
    ]
