# Generated by Django 2.2 on 2020-10-12 00:47

import datetime
from django.db import migrations, models
import ownerships.models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0014_auto_20201011_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentperiod',
            name='minDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
