# Generated by Django 2.2 on 2020-10-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0021_auto_20201025_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='rentPeriods',
        ),
        migrations.AddField(
            model_name='rentperiod',
            name='ownership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ownerships.Ownership'),
        ),
    ]
