# Generated by Django 2.2 on 2020-10-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerships', '0023_auto_20201025_1905'),
        ('ownerships', '0022_auto_20201025_1905'),
    ]

    operations = [
    ]
