# Generated by Django 2.2 on 2020-10-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='clientLastName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='clientName',
            field=models.CharField(max_length=30),
        ),
    ]
