# Generated by Django 2.2 on 2020-10-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201010_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
