# Generated by Django 2.2 on 2020-10-25 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20201011_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='creationDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
