# Generated by Django 2.2 on 2020-10-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20201024_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='totalPrice',
            field=models.FloatField(null=True),
        ),
    ]
