# Generated by Django 2.2 on 2020-10-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20201025_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
