# Generated by Django 2.2 on 2020-10-25 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20201025_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('1bf5b8f8-1716-11eb-9854-1c872c42c89b'), max_length=100),
        ),
    ]
