# Generated by Django 2.2 on 2020-10-25 23:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20201025_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('62db298a-1716-11eb-b314-1c872c42c89b'), max_length=100),
        ),
    ]
