# Generated by Django 2.2 on 2020-10-26 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20201025_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('ea32057a-1720-11eb-b2e6-e03f49459743'), max_length=100),
        ),
    ]
