# Generated by Django 2.2 on 2020-10-26 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20201025_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('2930d20c-17e5-11eb-b00c-1c872c42c89b'), max_length=100),
        ),
    ]
