# Generated by Django 2.2 on 2020-10-27 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20201025_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('5de91ff4-189b-11eb-89d7-e03f49459743'), max_length=100),
        ),
    ]
