# Generated by Django 2.2 on 2020-10-26 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20201026_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('867ea998-17e5-11eb-ba21-1c872c42c89b'), max_length=100),
        ),
    ]
