# Generated by Django 2.2 on 2020-10-26 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_auto_20201026_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('9d391d74-17e5-11eb-805e-1c872c42c89b'), max_length=100),
        ),
    ]
