# Generated by Django 2.2 on 2020-10-26 23:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20201026_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('eb9540c2-17e5-11eb-8399-1c872c42c89b'), max_length=100),
        ),
    ]
