# Generated by Django 2.2 on 2020-10-26 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_auto_20201026_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('d7a0bd9c-17e6-11eb-b39c-1c872c42c89b'), max_length=100),
        ),
    ]
