# Generated by Django 2.2 on 2020-10-26 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_auto_20201026_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('f7c71c46-17e6-11eb-8324-1c872c42c89b'), max_length=100),
        ),
    ]
