# Generated by Django 2.2 on 2020-10-27 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_auto_20201026_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('69866a9c-189c-11eb-ae78-b42e994d7310'), max_length=100),
        ),
    ]
