# Generated by Django 2.2 on 2020-10-28 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20201027_1828'),
        ('reservations', '0023_auto_20201027_2135'),
    ]

    operations = [
    ]
