# Generated by Django 2.2 on 2020-10-29 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_merge_20201027_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('1bd44198-1a2e-11eb-bdc8-1c872c42c89b'), max_length=100),
        ),
    ]
