# Generated by Django 2.2 on 2020-10-29 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_auto_20201029_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('4d8d3dfe-1a35-11eb-bfd0-e03f49459743'), max_length=100),
        ),
    ]
