# Generated by Django 2.2 on 2020-10-30 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0027_auto_20201029_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=uuid.UUID('717e0140-1ab4-11eb-a65d-e03f49459743'), max_length=100),
        ),
    ]
