# Generated by Django 2.2 on 2020-10-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('rentdates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdate',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Reservation'),
        ),
        migrations.AlterField(
            model_name='rentdate',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerships.Ownership'),
        ),
    ]
