# Generated by Django 2.2 on 2020-10-10 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentdates', '0002_auto_20201010_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdate',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
