# Generated by Django 2.2 on 2020-10-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentdates', '0003_auto_20201010_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdate',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation'),
        ),
    ]
